sudo: false

language: node_js

node_js:
  - '8'

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm install codecov.io coveralls

before_script:
    - yarn

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - yarn build

script:
  - yarn test:ci
  - yarn lint
