sudo: true

language: node_js

node_js:
  - 8.4

cache:
  directories:
    - node_modules

before_install:
  - npm i -g github-release-from-changelog

after_success:
  - npm i -g codecov.io coveralls
  - cat ./coverage/lcov.info | codecov
  - cat ./coverage/lcov.info | coveralls

script:
  - yarn lint
  - yarn build
  - yarn test:coverage

before_deploy:
  - echo '!dist/' >> .gitignore

deploy:
  - provider: pages
    name: Github Pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
      branch: master
  - provider: script
    github_token: $GITHUB_TOKEN
    script: github-release-from-changelog
    skip_cleanup: true
    on:
      tags: true
  - provider: heroku
    api_key:
      secure: $HEROKU_TOKEN
    skip_cleanup: true
    app: nfq-react-typescript
    on:
      branch: master
