sudo: true

language: node_js

node_js:
  - 8.4

cache:
  directories:
    - node_modules

after_success:
  - yarn global add codecov.io coveralls
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - gem install github_changelog_generator
  - github_changelog_generator --token $GITHUB_TOKEN --date-format %y/%m/%d
  - |
    changed_files=$(git diff --name-status "$TRAVIS_COMMIT_RANGE" | tr '\t' ' ')
    if [[ "$changed_files" == "M package.json" ]] ; then
      (
        git config --global user.email "builds@travis-ci.com"
        git config --global user.name "Travis CI"
        git add CHANGELOG.md
        git commit -m "Auto-update generate CHANGELOG.md from PR #$TRAVIS_PULL_REQUEST (https://github.com/$TRAVIS_REPO_SLUG/pull/$TRAVIS_PULL_REQUEST)."
        git push -q https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG --tags
      ) 2>&1 | sed -e "s/$GITHUB_TOKEN/REDACTED/g"
    else
      echo "Change log only updates if package.json is modified"
    fi

script:
  - yarn lint
  - yarn build
  - yarn test:coverage

deploy:
  - provider: pages
    name: Github Pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
      branch: master
  - provider: script
    script: yarn release:ci
    on:
      tags: true
