sudo: true

language: node_js

node_js:
  - 8.4

env:
  global:
    - BASE_PATH=$BASE_PATH

cache:
  directories:
    - node_modules

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
- git lfs pull
- npm i -g github-release-from-changelog

after_success:
  - npm i -g codecov.io coveralls
  - cat ./coverage/lcov.info | codecov
  - cat ./coverage/lcov.info | coveralls

script:
  - yarn lint
  - yarn build
  - yarn test:coverage

before_deploy:
  - export CI=false
deploy:
  - provider: pages
    name: Github Pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
      branch: master
  - provider: script
    github_token: $GITHUB_TOKEN
    script: github-release-from-changelog
    skip_cleanup: true
    on:
      tags: true
