sudo: true

language: node_js

node_js:
  - 8.4

cache:
  directories:
    - node_modules

branches:
  exclude:
  - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc
- git lfs pull
- yarn global add github-release-from-changelog

after_success:
  - yarn global add codecov.io coveralls
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

script:
  - yarn lint
  - yarn build
  - yarn test:coverage

deploy:
  - provider: pages
    name: Github Pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
      branch: master
  - provider: script
    github_token: $GITHUB_TOKEN
    script: github-release-from-changelog
    on:
      tag: true
